env:
  global:
    - CC_TEST_REPORTER_ID=d157dcd6681ab13e0bce28aa81be53b246e5299cf074f2d621612105aa023e88

language: python
python: 3.7.5

before_install:
  - pip install poetry

install:
  - make instale

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
